In [ ]:
import pandas as pd

In [4]:
df = pd.read_csv("../data/telco_customer_raw.csv")

In [5]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [6]:
import re
df.columns=[
    re.sub(r'(?!^)(?=[A-Z])','_',col).lower()
    for col in df.columns
]

In [7]:
df.head()

,customer_i_d,gender,senior_citizen,partner,dependents,tenure,phone_service,multiple_lines,internet_service,online_security,...,device_protection,tech_support,streaming_t_v,streaming_movies,contract,paperless_billing,payment_method,monthly_charges,total_charges,churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [8]:
df.isna().sum()

customer_i_d         0
gender               0
senior_citizen       0
partner              0
dependents           0
tenure               0
phone_service        0
multiple_lines       0
internet_service     0
online_security      0
online_backup        0
device_protection    0
tech_support         0
streaming_t_v        0
streaming_movies     0
contract             0
paperless_billing    0
payment_method       0
monthly_charges      0
total_charges        0
churn                0
dtype: int64

In [10]:
df[df.duplicated()]

Empty DataFrame
Columns: [customer_i_d, gender, senior_citizen, partner, dependents, tenure, phone_service, multiple_lines, internet_service, online_security, online_backup, device_protection, tech_support, streaming_t_v, streaming_movies, contract, paperless_billing, payment_method, monthly_charges, total_charges, churn]
Index: []

[0 rows x 21 columns]

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_i_d       7043 non-null   str
 1   gender             7043 non-null   str
 2   senior_citizen     7043 non-null   int64
 3   partner            7043 non-null   str
 4   dependents         7043 non-null   str
 5   tenure             7043 non-null   int64
 6   phone_service      7043 non-null   str
 7   multiple_lines     7043 non-null   str
 8   internet_service   7043 non-null   str
 9   online_security    7043 non-null   str
 10  online_backup      7043 non-null   str
 11  device_protection  7043 non-null   str
 12  tech_support       7043 non-null   str
 13  streaming_t_v      7043 non-null   str
 14  streaming_movies   7043 non-null   str
 15  contract           7043 non-null   str
 16  paperless_billing  7043 non-null   str
 17  payment_method     7043 non-null   str
 18  monthly_charges    7043 non-null   float64
 19  total_charges      7043 non-null   str
 20  churn              7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [31]:
df["phone_service"].value_counts()

phone_service
Yes    6361
No      682
Name: count, dtype: int64