In [65]:
import pandas as pd

In [66]:
df = pd.read_csv("../data/telco_customer_raw.csv")

In [67]:
df["OnlineSecurity"].value_counts

<bound method IndexOpsMixin.value_counts of 0        No
1       Yes
2       Yes
3       Yes
4        No
       ...
7038    Yes
7039     No
7040    Yes
7041     No
7042    Yes
Name: OnlineSecurity, Length: 7043, dtype: str>

In [68]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [69]:
df["gender"]=df["gender"].str.lower()

In [70]:
import re
df.columns=[
    re.sub(r'(?!^)(?=[A-Z])','_',col).lower()
    for col in df.columns
]

In [71]:
df.head()

,customer_i_d,gender,senior_citizen,partner,dependents,tenure,phone_service,multiple_lines,internet_service,online_security,...,device_protection,tech_support,streaming_t_v,streaming_movies,contract,paperless_billing,payment_method,monthly_charges,total_charges,churn
0,7590-VHVEG,female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [72]:
df.isna().sum()

customer_i_d         0
gender               0
senior_citizen       0
partner              0
dependents           0
tenure               0
phone_service        0
multiple_lines       0
internet_service     0
online_security      0
online_backup        0
device_protection    0
tech_support         0
streaming_t_v        0
streaming_movies     0
contract             0
paperless_billing    0
payment_method       0
monthly_charges      0
total_charges        0
churn                0
dtype: int64

In [73]:
df[df.duplicated()]

Empty DataFrame
Columns: [customer_i_d, gender, senior_citizen, partner, dependents, tenure, phone_service, multiple_lines, internet_service, online_security, online_backup, device_protection, tech_support, streaming_t_v, streaming_movies, contract, paperless_billing, payment_method, monthly_charges, total_charges, churn]
Index: []

[0 rows x 21 columns]

In [74]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_i_d       7043 non-null   str
 1   gender             7043 non-null   str
 2   senior_citizen     7043 non-null   int64
 3   partner            7043 non-null   str
 4   dependents         7043 non-null   str
 5   tenure             7043 non-null   int64
 6   phone_service      7043 non-null   str
 7   multiple_lines     7043 non-null   str
 8   internet_service   7043 non-null   str
 9   online_security    7043 non-null   str
 10  online_backup      7043 non-null   str
 11  device_protection  7043 non-null   str
 12  tech_support       7043 non-null   str
 13  streaming_t_v      7043 non-null   str
 14  streaming_movies   7043 non-null   str
 15  contract           7043 non-null   str
 16  paperless_billing  7043 non-null   str
 17  payment_method     7043 non-null   str
 18  monthly_charges    7043 non-null   float64
 19  total_charges      7043 non-null   str
 20  churn              7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [75]:
df["phone_service"].value_counts()

phone_service
Yes    6361
No      682
Name: count, dtype: int64

In [76]:
df.head(20)

,customer_i_d,gender,senior_citizen,partner,dependents,tenure,phone_service,multiple_lines,internet_service,online_security,...,device_protection,tech_support,streaming_t_v,streaming_movies,contract,paperless_billing,payment_method,monthly_charges,total_charges,churn
0,7590-VHVEG,female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
5,9305-CDSKC,female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes
6,1452-KIOVK,male,0,No,Yes,22,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Credit card (automatic),89.10,1949.4,No
7,6713-OKOMC,female,0,No,No,10,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,No,Mailed check,29.75,301.9,No
8,7892-POOKP,female,0,Yes,No,28,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes
9,6388-TABGU,male,0,No,Yes,62,Yes,No,DSL,Yes,...,No,No,No,No,One year,No,Bank transfer (automatic),56.15,3487.95,No
10,9763-GRSKD,male,0,Yes,Yes,13,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,49.95,587.45,No
11,7469-LKBCI,male,0,No,No,16,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),18.95,326.8,No
12,8091-TTVAX,male,0,Yes,No,58,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,No,Credit card (automatic),100.35,5681.1,No
13,0280-XJGEX,male,0,No,No,49,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes
14,5129-JLPIS,male,0,No,No,25,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,105.50,2686.05,No
15,3655-SNQYZ,female,0,Yes,Yes,69,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,No,Credit card (automatic),113.25,7895.15,No
16,8191-XWSZG,female,0,No,No,52,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,No,Mailed check,20.65,1022.95,No
17,9959-WOFKT,male,0,No,Yes,71,Yes,Yes,Fiber optic,Yes,...,Yes,No,Yes,Yes,Two year,No,Bank transfer (automatic),106.70,7382.25,No
18,4190-MFLUW,female,0,Yes,Yes,10,Yes,No,DSL,No,...,Yes,Yes,No,No,Month-to-month,No,Credit card (automatic),55.20,528.35,Yes
19,4183-MYFRB,female,0,No,No,21,Yes,No,Fiber optic,No,...,Yes,No,No,Yes,Month-to-month,Yes,Electronic check,90.05,1862.9,No

In [77]:
df.drop(columns='customer_i_d',inplace=True)

In [78]:
df['partner']=df['partner'].map({'Yes':1,'No':0})

In [79]:
df["phone_service"] = df["phone_service"].map({"Yes": 1, "No": 0})

In [80]:
df["dependents"] = df["dependents"].map({"Yes": 1, "No": 0})

In [81]:
df["paperless_billing"] = df["paperless_billing"].map({"Yes": 1, "No": 0})

In [82]:
print(df.columns)

Index(['gender', 'senior_citizen', 'partner', 'dependents', 'tenure',
       'phone_service', 'multiple_lines', 'internet_service',
       'online_security', 'online_backup', 'device_protection', 'tech_support',
       'streaming_t_v', 'streaming_movies', 'contract', 'paperless_billing',
       'payment_method', 'monthly_charges', 'total_charges', 'churn'],
      dtype='str')

In [83]:
import sklearn
from sklearn.preprocessing import OneHotEncoder

In [84]:
df=pd.get_dummies(df,columns=['contract'],dtype=int)

In [85]:
df.head()

,gender,senior_citizen,partner,dependents,tenure,phone_service,multiple_lines,internet_service,online_security,online_backup,...,streaming_t_v,streaming_movies,paperless_billing,payment_method,monthly_charges,total_charges,churn,contract_Month-to-month,contract_One year,contract_Two year
0,female,0,1,0,1,0,No phone service,DSL,No,Yes,...,No,No,1,Electronic check,29.85,29.85,No,1,0,0
1,male,0,0,0,34,1,No,DSL,Yes,No,...,No,No,0,Mailed check,56.95,1889.5,No,0,1,0
2,male,0,0,0,2,1,No,DSL,Yes,Yes,...,No,No,1,Mailed check,53.85,108.15,Yes,1,0,0
3,male,0,0,0,45,0,No phone service,DSL,Yes,No,...,No,No,0,Bank transfer (automatic),42.30,1840.75,No,0,1,0
4,female,0,0,0,2,1,No,Fiber optic,No,No,...,No,No,1,Electronic check,70.70,151.65,Yes,1,0,0

In [86]:
df=pd.get_dummies(df,columns=["gender"],drop_first=True,dtype=int)

In [87]:
df["churn"] = df["churn"].map({"Yes": 1, "No": 0})

In [88]:
df = pd.get_dummies(df, columns=["payment_method"], drop_first=True, dtype=int)

In [89]:
service_cols = [
    "multiple_lines",
    "internet_service",
    "online_security",
    "online_backup",
    "device_protection",
    "tech_support",
    "streaming_t_v",
    "streaming_movies",
]

In [90]:
df["total_charges"].str.strip().eq("").sum()

np.int64(11)

In [91]:
df[df["total_charges"].str.strip() == ""]

,senior_citizen,partner,dependents,tenure,phone_service,multiple_lines,internet_service,online_security,online_backup,device_protection,...,monthly_charges,total_charges,churn,contract_Month-to-month,contract_One year,contract_Two year,gender_male,payment_method_Credit card (automatic),payment_method_Electronic check,payment_method_Mailed check
488,0,1,1,0,0,No phone service,DSL,Yes,No,Yes,...,52.55,,0,0,0,1,0,0,0,0
753,0,0,1,0,1,No,No,No internet service,No internet service,No internet service,...,20.25,,0,0,0,1,1,0,0,1
936,0,1,1,0,1,No,DSL,Yes,Yes,Yes,...,80.85,,0,0,0,1,0,0,0,1
1082,0,1,1,0,1,Yes,No,No internet service,No internet service,No internet service,...,25.75,,0,0,0,1,1,0,0,1
1340,0,1,1,0,0,No phone service,DSL,Yes,Yes,Yes,...,56.05,,0,0,0,1,0,1,0,0
3331,0,1,1,0,1,No,No,No internet service,No internet service,No internet service,...,19.85,,0,0,0,1,1,0,0,1
3826,0,1,1,0,1,Yes,No,No internet service,No internet service,No internet service,...,25.35,,0,0,0,1,1,0,0,1
4380,0,1,1,0,1,No,No,No internet service,No internet service,No internet service,...,20.00,,0,0,0,1,0,0,0,1
5218,0,1,1,0,1,No,No,No internet service,No internet service,No internet service,...,19.70,,0,0,1,0,1,0,0,1
6670,0,1,1,0,1,Yes,DSL,No,Yes,Yes,...,73.35,,0,0,0,1,0,0,0,1
6754,0,0,1,0,1,Yes,DSL,Yes,Yes,No,...,61.90,,0,0,0,1,1,0,0,0

In [92]:
df = pd.get_dummies(df, columns=service_cols,drop_first=True, dtype=int)

In [93]:
df["total_charges"] = pd.to_numeric(df["total_charges"], errors="coerce").fillna(0.0)

In [97]:
pd.set_option("display.max_columns", None)
df.head(1)

,senior_citizen,partner,dependents,tenure,phone_service,paperless_billing,monthly_charges,total_charges,churn,contract_Month-to-month,contract_One year,contract_Two year,gender_male,payment_method_Credit card (automatic),payment_method_Electronic check,payment_method_Mailed check,multiple_lines_No phone service,multiple_lines_Yes,internet_service_Fiber optic,internet_service_No,online_security_No internet service,online_security_Yes,online_backup_No internet service,online_backup_Yes,device_protection_No internet service,device_protection_Yes,tech_support_No internet service,tech_support_Yes,streaming_t_v_No internet service,streaming_t_v_Yes,streaming_movies_No internet service,streaming_movies_Yes
0,0,1,0,1,0,1,29.85,29.85,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0

In [95]:
df.columns

Index(['senior_citizen', 'partner', 'dependents', 'tenure', 'phone_service',
       'paperless_billing', 'monthly_charges', 'total_charges', 'churn',
       'contract_Month-to-month', 'contract_One year', 'contract_Two year',
       'gender_male', 'payment_method_Credit card (automatic)',
       'payment_method_Electronic check', 'payment_method_Mailed check',
       'multiple_lines_No phone service', 'multiple_lines_Yes',
       'internet_service_Fiber optic', 'internet_service_No',
       'online_security_No internet service', 'online_security_Yes',
       'online_backup_No internet service', 'online_backup_Yes',
       'device_protection_No internet service', 'device_protection_Yes',
       'tech_support_No internet service', 'tech_support_Yes',
       'streaming_t_v_No internet service', 'streaming_t_v_Yes',
       'streaming_movies_No internet service', 'streaming_movies_Yes'],
      dtype='str')

In [96]:
df.to_csv("../data/clean_data.csv",index=False)